workloads:
  service_discovery:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: project
        value: chariott
    runtimeConfig: |
      image: sdvblueprint.azurecr.io/sdvblueprint/eclipse-chariott/service-discovery:0.1.1
      commandOptions: ["--network", "host"]
  mqtt_broker:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: project
        value: agemo
    runtimeConfig: |
      image: sdvblueprint.azurecr.io/sdvblueprint/eclipse-mosquitto/mqtt-broker:latest
      commandOptions: ["--network", "host"]
  dynamic_topic_management:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: project
        value: agemo
    runtimeConfig: |
      image: sdvblueprint.azurecr.io/sdvblueprint/eclipse-agemo/pub-sub-service:0.1.0
      commandOptions: ["--network", "host"]
  digital_twin_vehicle:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: project
        value: ibeji
    runtimeConfig: |
      image: sdvblueprint.azurecr.io/sdvblueprint/eclipse-ibeji/invehicle-digital-twin:0.1.0
      commandOptions: ["--network", "host"]
  digital_twin_cloud_sync:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: project
        value: freyja
    runtimeConfig: |
      image: sdvblueprint.azurecr.io/sdvblueprint/eclipse-freyja/local-with-ibeji:0.1.0
      commandOptions: ["--network", "host"]
  cloud_connector:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    runtimeConfig: |
      image: docker.io/library/nginx:latest
      commandOptions: ["--network", "host"]
  # resource_monitor:
  #   runtime: podman
  #   agent: agent_A
  #   restart: true
  #   updateStrategy: AT_MOST_ONCE
  #   accessRights:
  #     allow: []
  #     deny: []
  #   runtimeConfig: |
  #     image: ghcr.io/eclipse-ankaios/maestro_resource_monitor:latest
  #     commandOptions: ["--network", "host", "--privileged", "--pid", "host", "--hostname", "host_of_agentA"]